apiVersion: apps/v1
kind: Deployment
metadata:
  name: faction-auth
spec:
  selector:
    matchLabels:
      app: faction-auth
  template:
    metadata:
      labels:
        app: faction-auth
    spec:
      containers:
        - name: faction-auth
          image: faction/auth
          ports:
            - containerPort: 5000
          env:
            - name: FACTION_LOGGING_LEVEL
              value: "debug"
            - name: FACTION_FLASK_SECRET
              valueFrom:
                secretKeyRef:
                  key: flask-secret
                  name: auth-secrets
            - name: FACTION_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt-secret
                  name: auth-secrets
            - name: FACTION_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: admin-password
                  name: auth-secrets
            - name: FACTION_SYSTEM_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: system-password
                  name: auth-secrets
            - name: FACTION_DB_URI
              valueFrom:
                secretKeyRef:
                  key: db-url
                  name: db-secrets
