apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  jwt-secret: "c3VwZXJsb25ncGFzc3dvcmRleGFtcGxlaXNyZWFsbHlyZWFsbHlsb25n"
  admin-password: "UGFzc3dvcmQxMjM="
  system-password: "UGFzc3dvcmQxMjM="
